local_costmap:
  publish_voxel_map: true
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.01
  inflation_radius: 1.0
  # plugins:
  #   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
  #   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}